name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: archonium/package-lock.json
      - name: Install
        working-directory: archonium
        run: npm ci
      - name: Lint
        working-directory: archonium
        run: npm run lint
      - name: Build
        working-directory: archonium
        run: npm run build